# Site settings
title: Flight of thoughts
description: My personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://creamy.me" # the base hostname & protocol for your site
default_image: /media/about-bg.jpg
# Build settings
markdown: kramdown
paginate: 7
paginate_path: "/arhive/page:num"
gems: [jekyll-paginate]
